# Generated by Django 4.1.7 on 2024-08-15 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Название")),
                (
                    "url",
                    models.SlugField(
                        default="", max_length=200, unique=True, verbose_name="URL"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="", verbose_name="Фото"
                    ),
                ),
                ("description", models.TextField(default="", verbose_name="Описание")),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Фото", max_length=200, verbose_name="Название"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="", verbose_name="Фото"
                    ),
                ),
            ],
            options={
                "verbose_name": "Галерея",
                "verbose_name_plural": "Галереи",
            },
        ),
        migrations.CreateModel(
            name="Pricelist",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Название")),
                ("price", models.FloatField(verbose_name="Цена")),
            ],
            options={
                "verbose_name": "Прайс-лист",
                "verbose_name_plural": "Прайс-листы",
            },
        ),
        migrations.CreateModel(
            name="SCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, verbose_name="Название категории"),
                ),
                (
                    "url",
                    models.SlugField(
                        default="", max_length=200, unique=True, verbose_name="URL"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="", verbose_name="Фото"
                    ),
                ),
                ("description", models.TextField(default="", verbose_name="Описание")),
            ],
            options={
                "verbose_name": "Категория услуг",
                "verbose_name_plural": "Категории услуг",
            },
        ),
        migrations.CreateModel(
            name="SProduct",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Название услуги"),
                ),
                ("price", models.FloatField(verbose_name="Цена")),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="", verbose_name="Фото"
                    ),
                ),
                ("description", models.TextField(default="", verbose_name="Описание")),
                ("contact", models.TextField(default="", verbose_name="Контакты")),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="store.scategory",
                        verbose_name="Катерогия услуг",
                    ),
                ),
            ],
            options={
                "verbose_name": "Услуга",
                "verbose_name_plural": "Услуги",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Название")),
                ("price", models.FloatField(verbose_name="Цена")),
                (
                    "availability",
                    models.BooleanField(
                        blank=True, default=False, null=True, verbose_name="В наличии"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="", verbose_name="Фото"
                    ),
                ),
                ("description", models.TextField(default="", verbose_name="Описание")),
                ("contact", models.TextField(default="", verbose_name="Контакты")),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="store.category",
                        verbose_name="Катерогия товаров",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
            },
        ),
    ]
